Small changes and possible bug fixes
mdfeatureselection/mdfs-py pull request #2
Opened 2023-08-29 14:19 UTC by balaram26

Changes have been made on: fit_p_value,compute_ig and compute_tuples. Check the commit log for detailed information.

2023-09-01 11:49 UTC, yoctozepto requested changes

2023-09-01 11:49 UTC, yoctozepto commented on .vscode/c_cpp_properties.json
> +{
We don't want to commit this.

2023-09-01 11:49 UTC, yoctozepto commented on .gitignore
> +build/*
Why are these extra ignores needed? We should not need them. They feel arbitrary.

2023-09-01 11:49 UTC, yoctozepto commented on data/MDFS_Result_python_1D.json
> +        0.20721572256977003,
Any idea why these values have changed?

2023-09-01 11:49 UTC, yoctozepto commented on example_mdfs_run.json
> +{"contrast_indices":
Some broken file.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +
Needless line.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +
Needless ws.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +    range_ = -1
Good catch. These two lines should have been dropped.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +
Needless ws.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +
Needless line and code-comment.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_max_ig.py
> +def prepare_integer_in_bounds(x, x_desc, lower_bound, upper_bound):
Not used.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_tuples.py
> +def compute_tuples_discrete(data, decision=None, *, divisions = 1, dimensions=2, pc_xi=0.25,
Should not be here (discussed already).

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/compute_tuples.py
> +    # divisions = len(set(data)) - 1
This should stay as is for now. We might want to add more user-friendliness in here but it's not mandatory since we want to reimplement this anyway.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/fit_p_value.py
> +                exponential_fit=None,
It does not make sense to have a default here. It was on purpose.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/fit_p_value.py
> +    if chisq_contrast!= None:
We don't need to play with it. The error handling has been added by you in C++ code and it's enough.

2023-09-01 11:49 UTC, yoctozepto commented on mdfs/run.py
> +
Needless ws.

2023-09-01 11:49 UTC, yoctozepto commented on setup.py
> +            extra_compile_args=['-std=c++14', '-Wall', '-Wextra'],  # Add your compiler flags here
Why so?

2023-09-01 11:49 UTC, yoctozepto commented on shared/interface/fit_p_value.cpp
> -
This line was separating custom headers from system headers for readability.

2023-09-01 11:49 UTC, yoctozepto commented on shared/src/cpu/PrintUtility.h
> +#ifndef PRINT_UTILITY_H
Why this? It's not used.

2023-09-01 13:08 UTC, balaram26 commented on .gitignore
> +build/*
I have some test data and also some example scripts on my local system. i didn't want them to be committed at that stage as some are just test. once its fully done, I might add them as example test scripts in python, so I let them b ignored for now.

2023-09-01 13:09 UTC, balaram26 commented on data/MDFS_Result_python_1D.json
> +        0.20721572256977003,
no, i dont remember working with this file. so not sure. i saw somehow the file was modified, was not sure. we can ignore these changes.

2023-09-01 13:12 UTC, balaram26 commented on mdfs/compute_max_ig.py
> +
i had left those in case we wanted to apply some division-related operations, they were a replication of the R-code.

2023-09-01 13:13 UTC, balaram26 commented on mdfs/compute_max_ig.py
> +def prepare_integer_in_bounds(x, x_desc, lower_bound, upper_bound):
Again, it was division related code, implementation of R-code function. kept them as optional if you wanted to apply division-related suggestions. We can remove those now I guess.

2023-09-01 13:15 UTC, balaram26 commented on shared/src/cpu/PrintUtility.h
> +#ifndef PRINT_UTILITY_H
It was my handy file to print things and see data at every step for testing. Thought I removed it at last before committing the files.

2023-09-06 10:49 UTC, yoctozepto commented
@balaram26 Are you planning to update this PR?

2023-10-08 17:15 UTC, balaram26 commented
Hey i have addressed all issues you asked here, do I need to update code on my side or you can just not accept those not needed changes and do merging for accepted one alone? this way I can fetch and then do next pull after that? @yoctozepto

2023-10-14 20:04 UTC, closed without merging